[package]
name = "mx8-manifest-store"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
mx8-core = { path = "../mx8-core" }
thiserror.workspace = true

[dev-dependencies]
anyhow.workspace = true
