[package]
name = "mx8-snapshot"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
mx8-core = { path = "../mx8-core" }
mx8-manifest-store = { path = "../mx8-manifest-store" }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
anyhow.workspace = true
