[package]
name = "mx8-runtime"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
mx8-core = { path = "../mx8-core" }
anyhow.workspace = true
tracing.workspace = true

