[package]
name = "mx8-wire"
version = "1.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
mx8-core = { path = "../mx8-core" }
mx8-proto = { path = "../mx8-proto" }
thiserror.workspace = true

